In [1]:
import numpy as np
np.array([10])

array(10)

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [7]:
m=np.array([[7,5,4],[5,7,6]])
m


array([[7, 5, 4],
       [5, 7, 6]])

In [11]:
m.shape

(2, 3)

In [12]:
b=np.arange(0,50,7)

In [13]:
b

array([ 0,  7, 14, 21, 28, 35, 42, 49])

In [15]:
b.reshape(4,2)

array([[ 0,  7],
       [14, 21],
       [28, 35],
       [42, 49]])

In [16]:
b.reshape(2,4)

array([[ 0,  7, 14, 21],
       [28, 35, 42, 49]])

In [17]:
y=np.linspace(0,7,4)

In [18]:
y

array([0.        , 2.33333333, 4.66666667, 7.        ])

In [19]:
y.resize(2,2)

In [20]:
y

array([[0.        , 2.33333333],
       [4.66666667, 7.        ]])

In [23]:
np.ones((7,7),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]])

In [24]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.eye(6,6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [28]:
np.eye(5,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [29]:
np.diag(y)

array([0., 7.])

In [30]:
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [31]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [32]:
np.repeat([1,2,3,4,5,6,7,8,9],7)

array([1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7,
       7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9])

In [33]:
p=np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
np.vstack([p,2*p,6*p*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [6, 6, 6],
       [6, 6, 6]])

In [38]:
np.hstack([p,2*p,3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [39]:
print(y*6)

[[ 0. 14.]
 [28. 42.]]


In [47]:
k=np.arange(0,4)
k

array([0, 1, 2, 3])

In [48]:
k.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [50]:
l=np.linspace(7,5,9)

In [51]:
l

array([7.  , 6.75, 6.5 , 6.25, 6.  , 5.75, 5.5 , 5.25, 5.  ])

## 

In [54]:
x=np.array([1,2,3,4])
x.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [56]:
y=np.array([1,2,3,4])
y.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [59]:
print(x/y)

[1. 1. 1. 1.]


In [60]:
print(x*y)

[ 1  4  9 16]


In [61]:
print(x@y)

30


In [64]:
z=np.array([y,y**2])
z

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [66]:
z.shape

(2, 4)

In [67]:
z.T

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [68]:
z.T.shape

(4, 2)

In [70]:
z.dtype

dtype('int32')

In [73]:
z=z.astype('f')
z
z.dtype
z

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  4.,  9., 16.]], dtype=float32)

In [74]:
x.dot(y)

30

In [75]:
c=np.array([5,6,4,3,-9])

In [76]:
c.sum()

9

In [78]:
c.min()

-9

In [79]:
c.max()

6

In [80]:
c.mean()

1.8

In [82]:
c.std()

5.491812087098393

In [83]:
c.argmax()

1

In [84]:
c.argmin()

4

In [87]:
j=np.arange(100)**2
j

array([   0,    1,    4,    9,   16,   25,   36,   49,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361,  400,  441,
        484,  529,  576,  625,  676,  729,  784,  841,  900,  961, 1024,
       1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849,
       1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916,
       3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225,
       4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776,
       5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569,
       7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604,
       9801], dtype=int32)

In [89]:
j.reshape(10,10)

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401],
       [2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481],
       [3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761],
       [4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241],
       [6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921],
       [8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]],
      dtype=int32)

In [90]:
j[0],j[9],j[7]

(0, 81, 49)

In [91]:
j[9:]

array([  81,  100,  121,  144,  169,  196,  225,  256,  289,  324,  361,
        400,  441,  484,  529,  576,  625,  676,  729,  784,  841,  900,
        961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681,
       1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704,
       2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969,
       4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476,
       5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225,
       7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216,
       9409, 9604, 9801], dtype=int32)

In [92]:
j[0:5]

array([ 0,  1,  4,  9, 16], dtype=int32)

In [94]:
j[-6:]

array([8836, 9025, 9216, 9409, 9604, 9801], dtype=int32)

In [95]:
j[-9::-5]

array([8281, 7396, 6561, 5776, 5041, 4356, 3721, 3136, 2601, 2116, 1681,
       1296,  961,  676,  441,  256,  121,   36,    1], dtype=int32)

In [98]:
r=np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [99]:
r[2,2]

14

In [102]:
r[3,3:6]

array([21, 22, 23])

In [103]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [104]:
r[-1,::2]

array([30, 32, 34])

In [105]:
r[r>30]

array([31, 32, 33, 34, 35])

In [106]:
r[r>30]==0

array([False, False, False, False, False])

In [107]:
r[r>30]=0
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30,  0,  0,  0,  0,  0]])

In [109]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [110]:
r2[:]=0

In [112]:
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [113]:
r

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [114]:
r_copy=r.copy()
r_copy

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [115]:
r_copy[:]=10
r_copy

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [116]:
r

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [117]:
r==r_copy

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [118]:
test=np.random.randint(1,10,(4,3))

In [119]:
test

array([[9, 7, 5],
       [4, 5, 2],
       [2, 5, 9],
       [1, 9, 1]])

In [122]:
for row in test:
    print(row)

[9 7 5]
[4 5 2]
[2 5 9]
[1 9 1]


In [123]:
for i in range(len(test)):
    print(test[i])

[9 7 5]
[4 5 2]
[2 5 9]
[1 9 1]


In [124]:
for i,row in enumerate(row):
    print("row",i ,"is",row)

row 0 is 1
row 1 is 9
row 2 is 1


In [125]:
train=np.random.randint(4,9,(7,6))

In [126]:
train

array([[4, 6, 4, 6, 5, 4],
       [7, 8, 6, 6, 5, 7],
       [8, 6, 4, 4, 8, 6],
       [7, 7, 6, 5, 6, 7],
       [7, 5, 6, 7, 8, 5],
       [7, 8, 8, 6, 8, 8],
       [6, 5, 6, 8, 8, 7]])

In [130]:
for i in train:
    print (i)

[4 6 4 6 5 4]
[7 8 6 6 5 7]
[8 6 4 4 8 6]
[7 7 6 5 6 7]
[7 5 6 7 8 5]
[7 8 8 6 8 8]
[6 5 6 8 8 7]


In [132]:
for i,row in enumerate(row):
    print(i,row)

TypeError: 'numpy.int32' object is not iterable

In [134]:
test1=test**2
test1

array([[6561, 2401,  625],
       [ 256,  625,   16],
       [  16,  625, 6561],
       [   1, 6561,    1]], dtype=int32)

In [136]:
for i,j in zip(test1,test):
    print(i+j)

[6642 2450  650]
[272 650  20]
[  20  650 6642]
[   2 6642    2]


In [141]:
a=np.arange(36)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [143]:
a.resize(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [144]:
a[::7]

array([[0, 1, 2, 3, 4, 5]])

In [145]:
a[0:6,::-7]

array([[ 5],
       [11],
       [17],
       [23],
       [29],
       [35]])

In [146]:
a[:,::7]

array([[ 0],
       [ 6],
       [12],
       [18],
       [24],
       [30]])

In [147]:
a.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [148]:
a[2:4,2:4]

array([[14, 15],
       [20, 21]])